language: c
dist: trusty

matrix:
    include:
        - os: linux
          env: BUILD=x86_64-linux-gnu
          compiler: gcc

        - os: linux
          env: BUILD=i686-linux-gnu CFLAGS=-m32
          addons:
              apt:
                  packages:
                      - gcc-multilib
          compiler: gcc

        - os: linux
          env: BUILD=x86_64-linux-gnu
          compiler: clang

        - os: linux
          env: BUILD=i686-linux-gnu CFLAGS=-m32
          compiler: clang
          addons:
              apt:
                  packages:
                      - gcc-multilib

script:
    - ./bootstrap && ./configure --enable-remote-bitbang --enable-jtag_vpi && make
    - file src/openocd
